version: '3'
services:
  app:
    container_name: app_container
    build: ./docker/app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
      VUE_APP_API_ENDPOINT: http://localhost:5000
    command: npm run serve
  api:
    container_name: api_container
    image: node:14.15.1-alpine
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    command: node api/index.js
